name: SimpleLay
main: brokiem\simplelay\SimpleLay
version: 2.0.0
api: 3.13.0
author: brokiem

commands:
  lay:
    description: "lay on a block"
    permission: simplelay.lay
    usage: /lay

permissions:
  simplelay.lay:
    default: true
    description: "permission to allow the use of lay command"